CREATE SCHEMA IF NOT EXISTS public;

DROP TABLE IF EXISTS public.test_data_types;

CREATE TABLE IF NOT EXISTS public.test_data_types (
	_BIGINT BIGINT,
	_BIT BIT,
	_BOOLEAN BOOLEAN,
	_BLOB BYTEA, -- changed same size
	_DATE DATE,
	_DOUBLE DOUBLE PRECISION, -- changed same size
	_DECIMAL DECIMAL(18, 4),
  --_HUGEINT HUGEINT, -- no match
	_INTEGER INTEGER,
	_INTERVAL INTERVAL,
	_REAL REAL,
	_SMALLINT SMALLINT,
	_TIME TIME,
	_TIMESTAMP TIMESTAMP,
	_TIMESTAMP2 TIMESTAMP WITH TIME ZONE,
	_TINYINT SMALLINT, -- changed different size
  --_UBIGINT UBIGINT, -- no match
  --_UINTEGER UINTEGER, -- no match
  --_USMALLINT USMALLINT, -- no match
  --_UTINYINT UTINYINT, -- no match
	_UUID UUID,
	_VARCHAR VARCHAR
);